const mongoose = require('mongoose');

const visitorSchema = new mongoose.Schema({
    visitorName: { type: String, required: true },
    mobileNumber: { type: String, required: true },
    visitingResident: { 
        type: mongoose.Schema.Types.ObjectId, 
        ref: 'Resident', 
        required: false   // made optional — guard may not always select a resident
    },
    blockWing: { type: String, required: true },
    flatNumber: { type: String, required: true },
    purpose: { type: String, required: true },
    visitorKey: { type: String, default: "" },  // OTP key generated by guard
    entryTime: { type: Date, default: Date.now },
    exitTime: { type: Date },
    status: { type: String, enum: ['Pending', 'inside', 'Exited'], default: 'inside' }
}, { timestamps: true });

module.exports = mongoose.model('Visitor', visitorSchema);